// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnqvRzbpfmWMg6Q12DrUHBKGZzX-PTouE',
    appId: '1:734017648363:web:2e507b70acdb96976b30ae',
    messagingSenderId: '734017648363',
    projectId: 'rdp-todolist-4b1cf',
    authDomain: 'rdp-todolist-4b1cf.firebaseapp.com',
    storageBucket: 'rdp-todolist-4b1cf.appspot.com',
    measurementId: 'G-85DQQ5MSGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCucH4FsyLXfkSsoslwNm63v8ImqBmsNVc',
    appId: '1:734017648363:android:6a027c5fb7ceaa496b30ae',
    messagingSenderId: '734017648363',
    projectId: 'rdp-todolist-4b1cf',
    storageBucket: 'rdp-todolist-4b1cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChu6BeeCj7RKNUUhBRPhP8vV-Hwl40RWQ',
    appId: '1:734017648363:ios:70a56ad09d33e7006b30ae',
    messagingSenderId: '734017648363',
    projectId: 'rdp-todolist-4b1cf',
    storageBucket: 'rdp-todolist-4b1cf.appspot.com',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChu6BeeCj7RKNUUhBRPhP8vV-Hwl40RWQ',
    appId: '1:734017648363:ios:70a56ad09d33e7006b30ae',
    messagingSenderId: '734017648363',
    projectId: 'rdp-todolist-4b1cf',
    storageBucket: 'rdp-todolist-4b1cf.appspot.com',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnqvRzbpfmWMg6Q12DrUHBKGZzX-PTouE',
    appId: '1:734017648363:web:8f4dc011339a443f6b30ae',
    messagingSenderId: '734017648363',
    projectId: 'rdp-todolist-4b1cf',
    authDomain: 'rdp-todolist-4b1cf.firebaseapp.com',
    storageBucket: 'rdp-todolist-4b1cf.appspot.com',
    measurementId: 'G-Y32RCDMBVC',
  );
}
