// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBicBvOCWVhtW2BSfpNjYPFpgYQ0kDC398',
    appId: '1:514546543937:web:e7eb430abfcd12ac5885c0',
    messagingSenderId: '514546543937',
    projectId: 'rdp-todolist-1234',
    authDomain: 'rdp-todolist-1234.firebaseapp.com',
    storageBucket: 'rdp-todolist-1234.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8nWS75iRpz3HxsCHLXK1Z1iV_2JKErtI',
    appId: '1:514546543937:android:6e1ab418744119e75885c0',
    messagingSenderId: '514546543937',
    projectId: 'rdp-todolist-1234',     
    storageBucket: 'rdp-todolist-1234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDi1owWy75t_v4KmWHG1I2jjPyVZo1hls',
    appId: '1:514546543937:ios:1dfa4397684d0a4d5885c0',
    messagingSenderId: '514546543937',
    projectId: 'rdp-todolist-1234',
    storageBucket: 'rdp-todolist-1234.appspot.com',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDi1owWy75t_v4KmWHG1I2jjPyVZo1hls',
    appId: '1:514546543937:ios:1dfa4397684d0a4d5885c0',
    messagingSenderId: '514546543937',
    projectId: 'rdp-todolist-1234',
    storageBucket: 'rdp-todolist-1234.appspot.com',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBicBvOCWVhtW2BSfpNjYPFpgYQ0kDC398',
    appId: '1:514546543937:web:61974c428b1d7c495885c0',
    messagingSenderId: '514546543937',
    projectId: 'rdp-todolist-1234',
    authDomain: 'rdp-todolist-1234.firebaseapp.com',
    storageBucket: 'rdp-todolist-1234.appspot.com',
  );

}